
CREATE TABLE MENU (
    ID INT IDENTITY(1,1) PRIMARY KEY CONSTRAINT PK_MENU,
    NAME NVARCHAR(100),
    ACTIVE_FLAG BIT,
    PRIMARY_FLAG BIT,
    ORDER_NUMBER INT,
    ICON_NAME NVARCHAR(45),
    MENU_HIGHER_ID INT,
    CONSTRAINT FK_MENU_SELF FOREIGN KEY (MENU_HIGHER_ID) REFERENCES MENU(ID)
);

CREATE TABLE INTERFACE (
    ID INT IDENTITY(1,1) PRIMARY KEY CONSTRAINT PK_INTERFACE,
    MENU_ID INT,
    NAME NVARCHAR(100),
    URL_ADDRESS NVARCHAR(200),
    ORDER_NUMBER INT,
    ACTIVE_FLAG BIT,
    NEWS_FLAG BIT,
    ICON_NAME NVARCHAR(45),
    CONSTRAINT FK_INTERFACE_MENU FOREIGN KEY (MENU_ID) REFERENCES MENU(ID)
);

CREATE TABLE PERMISSION (
    ID INT IDENTITY(1,1) PRIMARY KEY CONSTRAINT PK_PERMISSION,
    NAME NVARCHAR(200),
    INTERFACE_ID INT,
    CODE NVARCHAR(100),
    CONSTRAINT FK_PERMISSION_INTERFACE FOREIGN KEY (INTERFACE_ID) REFERENCES INTERFACE(ID)
);

CREATE TABLE PLAN (
    ID INT IDENTITY(1,1) PRIMARY KEY CONSTRAINT PK_PLAN,
    NAME NVARCHAR(100)
);

CREATE TABLE PLAN_PERMISSION (
    PLAN_ID INT,
    PERMISSION_ID INT,
    PRIMARY KEY (PLAN_ID, PERMISSION_ID) CONSTRAINT PK_PLAN_PERMISSION,
    CONSTRAINT FK_PLAN_PERMISSION_PLAN FOREIGN KEY (PLAN_ID) REFERENCES PLAN(ID),
    CONSTRAINT FK_PLAN_PERMISSION_PERMISSION FOREIGN KEY (PERMISSION_ID) REFERENCES PERMISSION(ID)
);

CREATE TABLE PROFILE_SYSTEM (
    ID INT IDENTITY(1,1) PRIMARY KEY CONSTRAINT PK_PROFILE_SYSTEM,
    NAME NVARCHAR(80)
);

CREATE TABLE PROFILE_SYSTEM_PERMISSION (
    PROFILE_SYSTEM_ID INT,
    PERMISSION_ID INT,
    PRIMARY KEY (PROFILE_SYSTEM_ID, PERMISSION_ID) CONSTRAINT PK_PROFILE_SYSTEM_PERMISSION,
    CONSTRAINT FK_PROFILE_SYSTEM_PERMISSION_PROFILE_SYSTEM FOREIGN KEY (PROFILE_SYSTEM_ID) REFERENCES PROFILE_SYSTEM(ID),
    CONSTRAINT FK_PROFILE_SYSTEM_PERMISSION_PERMISSION FOREIGN KEY (PERMISSION_ID) REFERENCES PERMISSION(ID)
);

CREATE TABLE [USER] (
    ID INT IDENTITY(1,1) PRIMARY KEY CONSTRAINT PK_USER,
    PROFILE_SYSTEM_ID INT,
    COMPANY_ID INT,
    NAME NVARCHAR(80),
    CPF_NUMBER NVARCHAR(11),
    EMAIL NVARCHAR(100),
    PASSWORD NVARCHAR(512),
    RENEW_PASSWORD_FLAG BIT,
    ACTIVE_FLAG BIT,
    ACCOUNT_OWNER_FLAG BIT,
    CONSTRAINT FK_USER_PROFILE_SYSTEM FOREIGN KEY (PROFILE_SYSTEM_ID) REFERENCES PROFILE_SYSTEM(ID),
    CONSTRAINT FK_USER_COMPANY FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY(ID)
);

CREATE TABLE LOGIN_HISTORY (
    ID INT IDENTITY(1,1) PRIMARY KEY CONSTRAINT PK_LOGIN_HISTORY,
    USER_ID INT,
    LOGIN_DATE DATETIME2(6),
    BROWSER_NAME NVARCHAR(100),
    BROWSER_VERSION NVARCHAR(30),
    IP_NUMBER NVARCHAR(45),
    CONSTRAINT FK_LOGIN_HISTORY_USER FOREIGN KEY (USER_ID) REFERENCES [USER](ID)
);

CREATE TABLE COMPANY (
    ID INT IDENTITY(1,1) PRIMARY KEY CONSTRAINT PK_COMPANY,
    NAME NVARCHAR(100),
    CNPJ_NUMBER NVARCHAR(14),
    ACTIVE_FLAG BIT,
    PLAN_ID INT,
    CONSTRAINT FK_COMPANY_PLAN FOREIGN KEY (PLAN_ID) REFERENCES PLAN(ID)
);

CREATE TABLE TEMPLATE_COMPANY (
    ID INT IDENTITY(1,1) PRIMARY KEY CONSTRAINT PK_TEMPLATE_COMPANY,
    NAME NVARCHAR(80),
    COMPANY_ID INT,
    CONSTRAINT FK_TEMPLATE_COMPANY_COMPANY FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY(ID)
);

CREATE TABLE TEMPLATE_COMPANY_PERMISSION (
    TEMPLATE_COMPANY_ID INT,
    PERMISSION_ID INT,
    PRIMARY KEY (TEMPLATE_COMPANY_ID, PERMISSION_ID) CONSTRAINT PK_TEMPLATE_COMPANY_PERMISSION,
    CONSTRAINT FK_TEMPLATE_COMPANY_PERMISSION_TEMPLATE_COMPANY FOREIGN KEY (TEMPLATE_COMPANY_ID) REFERENCES TEMPLATE_COMPANY(ID),
    CONSTRAINT FK_TEMPLATE_COMPANY_PERMISSION_PERMISSION FOREIGN KEY (PERMISSION_ID) REFERENCES PERMISSION(ID)
);

CREATE TABLE USER_PERMISSION (
    USER_ID INT,
    PERMISSION_ID INT,
    PRIMARY KEY (USER_ID, PERMISSION_ID) CONSTRAINT PK_USER_PERMISSION,
    CONSTRAINT FK_USER_PERMISSION_USER FOREIGN KEY (USER_ID) REFERENCES [USER](ID),
    CONSTRAINT FK_USER_PERMISSION_PERMISSION FOREIGN KEY (PERMISSION_ID) REFERENCES PERMISSION(ID)
);
